apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Program Files\Kubernetes\kompose-windows-amd64.exe convert -f
      docker-compose.yml
    kompose.version: ""
  creationTimestamp: null
  labels:
    io.kompose.service: candidate
  name: candidate
spec:
  type: LoadBalancer
  ports:
  - name: "8097"
    port: 8097
    targetPort: 8097
  selector:
    io.kompose.service: candidate
status:
  loadBalancer: {}
