apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Program Files\Kubernetes\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.4.0 (c7964e7)
  creationTimestamp: null
  labels:
    io.kompose.service: client
  name: client
spec:
  type: LoadBalancer
  ports:
  - name: "80"
    port: 80
    targetPort: 9090
  selector:
    io.kompose.service: client
status:
  loadBalancer: {}
