apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Program Files\Kubernetes\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.4.0 (c7964e7)
  creationTimestamp: null
  labels:
    io.kompose.service: gateway
  name: gateway
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: gateway
    spec:
      containers:
      - image: garystafford/voter-api-gateway:0.2.23
        name: gateway
        ports:
        - containerPort: 8080
        resources: {}
        imagePullPolicy: Always # added manually
      restartPolicy: Always
status: {}
