apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Program Files\Kubernetes\kompose-windows-amd64.exe convert -f
      docker-compose.yml
    kompose.version: ""
  creationTimestamp: null
  labels:
    io.kompose.service: mongodb
  name: mongodb
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mongodb
    spec:
      containers:
      - args:
        - --smallfiles
        image: mongo:latest
        name: mongodb
        ports:
        - containerPort: 27017
        resources: {}
      restartPolicy: Always
status: {}
