apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Program Files\Kubernetes\kompose-windows-amd64.exe convert -f
      docker-compose.yml
    kompose.version: ""
  creationTimestamp: null
  labels:
    io.kompose.service: voter
  name: voter
spec:
  type: LoadBalancer
  ports:
  - name: "8099"
    port: 8099
    targetPort: 8099
  selector:
    io.kompose.service: voter
status:
  loadBalancer: {}
