apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Program Files\Kubernetes\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.4.0 (c7964e7)
  creationTimestamp: null
  labels:
    io.kompose.service: voter
  name: voter
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: voter
    spec:
      containers:
      - image: garystafford/voter-service:0.2.104
        name: voter
        ports:
        - containerPort: 8080
        resources: {}
        imagePullPolicy: Always # added manually
      restartPolicy: Always
status: {}
